### PR TITLE
Detect and report unusable device to user

### LINKED ISSUE #264: Detect U2F key and report incompatibility
- Yubico Authenticator version: any
- Operating system and version: any
- YubiKey model and version: FIDO U2F Security Key
- Bug description summary: Yubico Authenticator attempts to connect to a FIDO U2F Security Key, and appears to hang because it can't open a connection.

Steps to reproduce
---

Start Yubico Authenticator and plug in a FIDO U2F Security Key

Expected result
---

The application reports that the FIDO U2F Security Key is incompatible with the app.

Actual results
---

The application hangs on "Connecting to YubiKey...".

### PR DESCRIPTION
**Pull request by emlun**
This fixes #264.

### CODE REVIEW

File: qml/utils.js [hunk 1]
```diff
@@ -18,6 +18,22 @@ function startsWith(string, search, pos) {
...
+    if (items) {
+        for (var i = 0; i < items.length; ++i) {
+            if (items[i] === sought) {
+                return true
+            }
+        }
+    }
+    return false
+}
+
```
Comment (emlun) [inline qml/utils.js]: Apparently I refactored the call to this out, so this is actually unused...

Comment (emlun) [inline qml/utils.js]: Apparently I refactored the call to this out, so this is actually unused...
