### PR TITLE
Make sure the application is always visible on a monitor

### LINKED ISSUE #241: Yubico Authenticator opens outside monitors and can not be accessed
Thank you for opening an issue! If this is a bug report, please include the
following information:

- Yubico Authenticator version: 4.3.2
- Operating system and version: Windows 10 pro
- YubiKey model and version: Neo
- Bug description summary: 

Yubico Authenticator opens outside monitors and can not be accessed anymore.

Steps to reproduce
---

I am using two 4k monitors with a resolution of 3840x2160 each, where 2 is my main monitor.

monitors

When opening Authenticator for the first time it is centered on my main monitor 2. I can move the Authenticator on monitor 2 and close it. Evereything works as expected and the settings are store in the registry as follows:

settings1

**Problem: When i move the Authenticator to my monitor 1 and i close the Authentcator on monitor 1 i am not able to see it anymore. I can see Authenticator starting and that it seems to be left outside of monitor 1.** Following settings are stored in the windows registry:

settings2

Expected result
---

I expect that Authenticator to open at monitor 1 (on same location where i closed it) next time i start the application.

Actual results
---

Authenticator opens outside left montior 1. I can not see it and can not use it. I need to manually delete the registry settings in my windows registry.

Other info
---

Great work and a great tool so far :-) Hopefully this description can help solving this issue. I can test your fix, if there will be one.

### PR DESCRIPTION
**Pull request by fdennis**
Needs testing on all OSes

Fixes #241

### CODE REVIEW

File: main.cpp [hunk 1]
```diff
@@ -46,6 +47,29 @@ int main(int argc, char *argv[])
     application.setOrganizationName("Yubico");
     application.setOrganizationDomain("com.yubico");
 
+    QDesktopWidget * desktop = QApplication::desktop();
+
+    // Get x and y coordinates of all monitors
+    QVariantList monitorList;
```
Comment (dagheyman) [inline main.cpp]: Maybe call this monitorAreas ?

File: main.cpp [hunk 2]
```diff
@@ -46,6 +47,29 @@ int main(int argc, char *argv[])
...
+    for (qint32 i = 0, screens = desktop->screenCount(); i < screens; i++)  {
+        QRect monitor = desktop->screenGeometry(i);
```
Comment (dagheyman) [inline main.cpp]: This could then be called monitorArea

File: qml/main.qml [hunk 3]
```diff
@@ -318,7 +336,9 @@ ApplicationWindow {
         interval: 1000
         repeat: true
         running: app.isInForeground || settings.closeToTray
-        onTriggered: yubiKey.poll()
+        onTriggered: {
```
Comment (dagheyman) [inline qml/main.qml]: Unrelated formatting change, remove

File: qml/main.qml [hunk 4]
```diff
@@ -139,6 +139,24 @@ ApplicationWindow {
...
+            var miny = monitorList[i+1].first
+            var maxy = monitorList[i+1].second
+
+            if (app.x > minx && app.x < maxx) {
+                if (app.y > miny && app.y < maxy) {
+                    return
+                }
+            }
+        }
+
```
Comment (dagheyman) [inline qml/main.qml]: We should probably add a comment here, that this is the fallback when the saved position seems to be outside of the available screen geometry, and we then just put the app in the middle of the screen.

File: main.cpp [hunk 5]
```diff
@@ -46,6 +47,29 @@ int main(int argc, char *argv[])
...
+
+        QVariantMap x;
+        QVariantMap y;
+
+        int monitor_x_min = monitor.x();
+        int monitor_x_max = monitor_x_min + monitor.width();
+        x.insert("first", monitor_x_min);
```
[the remark this answers is not in the document]
Comment (braathen) [reply main.cpp]: what if there's 3 (or more) monitors?

[the remark this answers is not in the document]
Comment (fdennis) [reply main.cpp]: > what if there's 3 (or more) monitors?

That does not matter. In this code we are storing the coordinates of every monitor. Every monitor has xmin, xmax, ymin, and ymax, since they are rectangles.

File: main.cpp [hunk 6]
```diff
@@ -46,6 +47,29 @@ int main(int argc, char *argv[])
     application.setOrganizationName("Yubico");
     application.setOrganizationDomain("com.yubico");
 
+    QDesktopWidget * desktop = QApplication::desktop();
+
+    // Get x and y coordinates of all monitors
+    QVariantList monitorList;
+    for (qint32 i = 0, screens = desktop->screenCount(); i < screens; i++)  {
```
Comment (emlun) [inline main.cpp]: I'm getting a deprecation warning in Qt 5.14:

```
main.cpp:54:55: warning: ‘int QDesktopWidget::screenCount() const’ is deprecated: Use QGuiApplication::screens() [-Wdeprecated-declarations]
   54 |     for (qint32 i = 0, screens = desktop->screenCount(); i < screens; i++)  {
      |                                                       ^
```

Looks like the non-deprecated API is something like this:

```cpp
    for (QScreen* screen : QGuiApplication::screens())  {
        QRect geometry = screen->geometry();
        // ...
        int monitor_x_min = geometry.x();
        // ...
    }
```

File: main.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (emlun) [reply main.cpp]: With that, we can also put both `xMin`/`xMax` and `yMin`/`yMax` in the same `QVariantMap` instead of having to add two per monitor.

File: qml/main.qml (hunk 4 above)
Comment (emlun) [reply qml/main.qml]: I agree, but I think even better would be to refactor the early return. For example by using a nested function:

```
        function windowPositionIsInsideSomeMonitor() {
            for (var i = 0; i < monitorList.length; i+=2)  {
                var minx = monitorList[i].first
                var maxx = monitorList[i].second
                var miny = monitorList[i+1].first
                var maxy = monitorList[i+1].second

                if (app.x > minx && app.x < maxx) {
                    if (app.y > miny && app.y < maxy) {
                        return
                    }
                }
            }
        }

        if (!windowPositionIsInsideSomeMonitor()) {
            app.x = Screen.width / 2 - app.width / 2
            app.y = Screen.height / 2 - app.height / 2
        }
```

File: main.cpp (hunk 6 above)
Comment (fdennis) [reply main.cpp]: Good catch!
